/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import App.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Venta extends javax.swing.JFrame {

    static Main obj1;
    
    
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        tituloJLabel = new javax.swing.JLabel();
        adn1JLabel = new javax.swing.JLabel();
        adn2JLabel = new javax.swing.JLabel();
        adn1TextField = new javax.swing.JTextField();
        adn2TextField = new javax.swing.JTextField();
        compararJButtom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        matchTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(102, 102, 102));

        tituloJLabel.setText("Analizador ADN");

        adn1JLabel.setText("ADN1");

        adn2JLabel.setText("ADN2");

        adn1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adn1TextFieldActionPerformed(evt);
            }
        });

        adn2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adn2TextFieldActionPerformed(evt);
            }
        });

        compararJButtom.setBackground(new java.awt.Color(0, 0, 0));
        compararJButtom.setForeground(new java.awt.Color(255, 255, 255));
        compararJButtom.setText("COMPARAR");
        compararJButtom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compararJButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compararJButtomActionPerformed(evt);
            }
        });

        matchTextArea.setColumns(20);
        matchTextArea.setRows(5);
        jScrollPane1.setViewportView(matchTextArea);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(adn1JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adn2JLabel)
                        .addGap(54, 54, 54))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(adn1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adn2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(tituloJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(compararJButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adn1JLabel)
                    .addComponent(adn2JLabel))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adn1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adn2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compararJButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adn1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adn1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adn1TextFieldActionPerformed

    private void adn2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adn2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adn2TextFieldActionPerformed

    private void compararJButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compararJButtomActionPerformed
        try{
            String adn1 = adn1TextField.getText();
            String adn2 = adn2TextField.getText();
            
            obj1 = new Main();
            obj1.setADNs(adn1, adn2);
            
        
            String palabra = obj1.getPalabra();
        
            matchTextArea.setText(palabra);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_compararJButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        JOptionPane.showMessageDialog(null, "Este programa reconoce solamente adns corridos\n"
                + "el insertar un adn, no ingrese espacios, todo corrido \n"
                + "EJ valido: adn1 : TTFFRREGGG\n"
                + "EJ no valido: TT GGADFA");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel adn1JLabel;
    private javax.swing.JTextField adn1TextField;
    private javax.swing.JLabel adn2JLabel;
    private javax.swing.JTextField adn2TextField;
    private javax.swing.JButton compararJButtom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea matchTextArea;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
